In [22]:
# for data
import pandas as pd
import numpy as np
from pandasgui import show
import os
import sys

import datetime

# for plotting
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
parent_folder = os.path.dirname(os.getcwd())

In [24]:
aviation_data_path = os.path.join(
    parent_folder, 'data', 'clean_aviation_data_2.csv')


df = pd.read_csv(aviation_data_path, encoding='latin-1')

In [25]:
# gui = show(df)

In [26]:
df.dtypes

Unnamed: 0               int64
location                object
injury_severity         object
aircraft_damage         object
make                    object
model                   object
number_of_engines      float64
engine_type             object
weather_conditions      object
phase_of_flight         object
Year                     int64
Month                    int64
Day                      int64
injuries               float64
pax_onboard            float64
fatality_percentage    float64
survived               float64
AmateurBuilt            object
dtype: object

In [27]:
df['injury_severity'] = df['injury_severity'].str.replace('\d+', '')

C:\Users\Makara PC\AppData\Local\Temp\ipykernel_9784\1768498327.py:1: FutureWarning:

The default value of regex will change from True to False in a future version.

In [28]:
cols = ['injury_severity']
for col in cols:
    df[col] = df[col].map(lambda x: str(x).lstrip(' ()').rstrip(' ()'))

In [29]:
df = df.rename(columns={'injury_severity': 'target',
               'AmateurBuilt': 'amateur_built'})

In [30]:
# gui = show(df)

In [31]:
df.replace({'target': {'Incident': 'Non-Fatal'}}, inplace=True)

In [32]:
df.head()

,Unnamed: 0,location,target,aircraft_damage,make,model,number_of_engines,engine_type,weather_conditions,phase_of_flight,Year,Month,Day,injuries,pax_onboard,fatality_percentage,survived,amateur_built
0,0,"CAMBRIA, NY",Non-Fatal,Destroyed,Unknown,64,1.0,Reciprocating,VMC,CLIMB,1982,6,13,1.0,1.0,0.0,1.0,No
1,1,"MCWHORTER, KY",Non-Fatal,Destroyed,Unknown,KR-2,1.0,Reciprocating,VMC,CRUISE,1982,7,1,2.0,2.0,0.0,2.0,Yes
2,2,"FREDERICK, MD",Fatal,Destroyed,Unknown,WINDWAGON,1.0,Reciprocating,VMC,APPROACH,1982,7,16,1.0,1.0,100.0,0.0,Yes
3,3,"VENTURA, CA",Non-Fatal,Destroyed,Unknown,MIDGET MUSTANG,1.0,Reciprocating,VMC,MANEUVERING,1982,8,21,0.0,1.0,0.0,1.0,Yes
4,4,"SIDNEY, NE",Non-Fatal,Substantial,Unknown,SKYBOLT,1.0,Reciprocating,VMC,LANDING,1982,8,24,0.0,1.0,0.0,1.0,Yes

In [33]:
df.target.value_counts(ascending=False)

Non-Fatal    39511
Fatal         9150
Name: target, dtype: int64

In [34]:
df.dtypes

Unnamed: 0               int64
location                object
target                  object
aircraft_damage         object
make                    object
model                   object
number_of_engines      float64
engine_type             object
weather_conditions      object
phase_of_flight         object
Year                     int64
Month                    int64
Day                      int64
injuries               float64
pax_onboard            float64
fatality_percentage    float64
survived               float64
amateur_built           object
dtype: object

In [39]:
df.head()

,Unnamed: 0,location,target,aircraft_damage,make,model,number_of_engines,engine_type,weather_conditions,phase_of_flight,Year,Month,Day,injuries,pax_onboard,fatality_percentage,survived,amateur_built
0,0,"CAMBRIA, NY",Non-Fatal,Destroyed,Unknown,64,1.0,Reciprocating,VMC,CLIMB,1982,6,13,1.0,1.0,0.0,1.0,No
1,1,"MCWHORTER, KY",Non-Fatal,Destroyed,Unknown,KR-2,1.0,Reciprocating,VMC,CRUISE,1982,7,1,2.0,2.0,0.0,2.0,Yes
2,2,"FREDERICK, MD",Fatal,Destroyed,Unknown,WINDWAGON,1.0,Reciprocating,VMC,APPROACH,1982,7,16,1.0,1.0,100.0,0.0,Yes
3,3,"VENTURA, CA",Non-Fatal,Destroyed,Unknown,MIDGET MUSTANG,1.0,Reciprocating,VMC,MANEUVERING,1982,8,21,0.0,1.0,0.0,1.0,Yes
4,4,"SIDNEY, NE",Non-Fatal,Substantial,Unknown,SKYBOLT,1.0,Reciprocating,VMC,LANDING,1982,8,24,0.0,1.0,0.0,1.0,Yes

In [38]:
df.columns

Index(['Unnamed: 0', 'location', 'target', 'aircraft_damage', 'make', 'model',
       'number_of_engines', 'engine_type', 'weather_conditions',
       'phase_of_flight', 'Year', 'Month', 'Day', 'injuries', 'pax_onboard',
       'fatality_percentage', 'survived', 'amateur_built'],
      dtype='object')

In [14]:

# Encoding categorical data values (Transforming object data types to integers)
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

# label vs hot_encoder???

# Encode location column
df.iloc[:, 1] = labelencoder.fit_transform(df.iloc[:, 1].values)

# Encode target column
df.iloc[:, 0] = labelencoder.fit_transform(df.iloc[:, 0].values)


# Encode aircraft_damage
df.iloc[:, 2] = labelencoder.fit_transform(df.iloc[:, 2].values)

# Encode make
df.iloc[:, 3] = labelencoder.fit_transform(df.iloc[:, 3].values)

# Encode model
df.iloc[:, 4] = labelencoder.fit_transform(df.iloc[:, 4].values)

# Encode engine_type
df.iloc[:, 6] = labelencoder.fit_transform(df.iloc[:, 6].values)

# Encode weather_conditions
df.iloc[:, 7] = labelencoder.fit_transform(df.iloc[:, 7].values)

# Encode phase_of_flight
df.iloc[:, 8] = labelencoder.fit_transform(df.iloc[:, 8].values)

# Encode amateur_built
df.iloc[:, 16] = labelencoder.fit_transform(df.iloc[:, 16].values)

C:\Users\Makara PC\AppData\Local\Temp\ipykernel_9784\3813467180.py:8: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

C:\Users\Makara PC\AppData\Local\Temp\ipykernel_9784\3813467180.py:15: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

C:\Users\Makara PC\AppData\Local\Temp\ipykernel_9784\3813467180.py:18: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

C:\Users\Makara PC\AppData\Local\Temp\ipykernel_9784\3813467180.py:21: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

C:\Users\Makara PC\AppData\Local\Temp\ipykernel_9784\3813467180.py:24: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

C:\Users\Makara PC\AppData\Local\Temp\ipykernel_9784\3813467180.py:27: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

C:\Users\Makara PC\AppData\Local\Temp\ipykernel_9784\3813467180.py:30: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

C:\Users\Makara PC\AppData\Local\Temp\ipykernel_9784\3813467180.py:33: DeprecationWarning:

In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`

In [15]:
df.head()

,Unnamed: 0,location,target,aircraft_damage,make,model,number_of_engines,engine_type,weather_conditions,phase_of_flight,Year,Month,Day,injuries,pax_onboard,fatality_percentage,survived,amateur_built
0,0,1725,1,0,2962,64,1,0,2,CLIMB,1982,6,13,1.0,1.0,0.0,1,No
1,1,7690,1,0,2962,KR-2,1,0,2,CRUISE,1982,7,1,2.0,2.0,0.0,2,Yes
2,2,4220,0,0,2962,WINDWAGON,1,0,2,APPROACH,1982,7,16,1.0,1.0,100.0,0,Yes
3,3,12732,1,0,2962,MIDGET MUSTANG,1,0,2,MANEUVERING,1982,8,21,0.0,1.0,0.0,1,Yes
4,4,11329,1,2,2962,SKYBOLT,1,0,2,LANDING,1982,8,24,0.0,1.0,0.0,1,Yes

In [16]:
# Encode model
df.iloc[:, 4] = labelencoder.fit_transform(df.iloc[:, 4].values)

In [17]:
# Encode phase_of_flight
df.iloc[:, 8] = labelencoder.fit_transform(df.iloc[:, 8].values)

In [18]:
# Encode amateur_built
df.iloc[:, 16] = labelencoder.fit_transform(df.iloc[:, 16].values)

In [19]:
df.head()

,Unnamed: 0,location,target,aircraft_damage,make,model,number_of_engines,engine_type,weather_conditions,phase_of_flight,Year,Month,Day,injuries,pax_onboard,fatality_percentage,survived,amateur_built
0,0,1725,1,0,2962,64,1,0,2,CLIMB,1982,6,13,1.0,1.0,0.0,1,No
1,1,7690,1,0,2962,KR-2,1,0,2,CRUISE,1982,7,1,2.0,2.0,0.0,2,Yes
2,2,4220,0,0,2962,WINDWAGON,1,0,2,APPROACH,1982,7,16,1.0,1.0,100.0,0,Yes
3,3,12732,1,0,2962,MIDGET MUSTANG,1,0,2,MANEUVERING,1982,8,21,0.0,1.0,0.0,1,Yes
4,4,11329,1,2,2962,SKYBOLT,1,0,2,LANDING,1982,8,24,0.0,1.0,0.0,1,Yes

In [20]:
df = df[['target', 'location', 'aircraft_damage',
         'make', 'model', 'number_of_engines', 'engine_type',
         'weather_conditions', 'phase_of_flight', 'Year',
                 'Month', 'Day', 'injuries', 'pax_onboard', 'fatality_percentage',
                 'survived', 'amateur_built']]

In [21]:
encoded_aviation_data_path = os.path.join(
    parent_folder, 'data', 'encoded_aviation_data_3.csv')

df.to_csv(encoded_aviation_data_path)

PermissionError: [Errno 13] Permission denied: 'c:\\Users\\Makara PC\\Documents\\Bluechip Technologies Asia\\ml-aviation-safety\\data\\encoded_aviation_data_3.csv'

In [25]:
viz_aviation_data_path = os.path.join(
    parent_folder, 'data', 'viz_aviation_data.csv')

df.to_csv(viz_aviation_data_path)